parameters:
  slotName: 'staging'
  appname: ''
  resourcegroupname: ''
  azuresubscription: 'Wedgewood-ARM'
  command: ''

steps:
- task: AzurePowerShell@4
  displayName: '${{parameters.command}} ${{parameters.slotName}} on ${{parameters.appname}}'
  inputs:
    azureSubscription: ${{parameters.azuresubscription}}
    ScriptType: InlineScript
    Inline: '${{parameters.command}}-AzureRmWebAppSlot 
                -ResourceGroupName ${{parameters.resourcegroupname}} 
                -Name ${{parameters.appname}} 
                -Slot ${{parameters.slotName}}'
    azurePowerShellVersion: LatestVersion